spring.application.name=Veranda

# Aiven Connection String
spring.datasource.url=jdbc:postgresql://pg-veranda-vigneshnc.b.aivencloud.com:18457/veranda_db
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_RMEe-DoMoj2j-BBnYMa
#spring.jpa.properties.hibernate.default_schema=veranda_schema

# SSL is REQUIRED for Aiven
spring.datasource.properties.ssl=true
spring.datasource.properties.sslmode=require

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.token.secret.key=your_very_long_and_very_secret_key_for_veranda_by_masterminds

#fast2sms.api.key=A9IzZUQu3PWpM8ohi1qRYN67XymnSTHxDEVwsLF2cBlgje5tdfFHqeU8j1Lor04Qn9J5iSVgdl6KDyaY

spring.jackson.deserialization.fail-on-null-for-primitives=false

# Limit the number of connections Spring Boot can hold
spring.datasource.hikari.maximum-pool-size=3
# How long to wait for a connection before failing
spring.datasource.hikari.connection-timeout=30000
# Keep idle connections low
spring.datasource.hikari.minimum-idle=1